# Generated by Django 2.0.6 on 2018-07-02 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('anho', models.DateField(db_column='Anho')),
                ('horario', models.CharField(db_column='Horario', max_length=32)),
                ('nombre', models.CharField(db_column='Nombre', max_length=64)),
                ('codigo', models.CharField(max_length=10)),
                ('ud', models.CharField(db_column='UD', max_length=10)),
            ],
            options={
                'db_table': 'cursos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=64)),
                ('sitioweb', models.CharField(blank=True, max_length=45, null=True)),
                ('codigo', models.CharField(db_column='Codigo', max_length=10)),
            ],
            options={
                'db_table': 'departamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RolUsuarioCurso',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'rol_usuario_curso',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Semestres',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_semestre', models.CharField(db_column='Nombre_Semestre', max_length=45)),
            ],
            options={
                'db_table': 'semestres',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=45)),
            ],
            options={
                'db_table': 'tipo_usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=64)),
                ('apellido', models.CharField(db_column='Apellido', max_length=64)),
                ('direccion', models.CharField(db_column='Direccion', max_length=128)),
                ('rut', models.CharField(db_column='RUT', max_length=32)),
                ('puntaje_psu', models.IntegerField(db_column='Puntaje_PSU')),
                ('username', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsuarioTipoUsuario',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'usuario_tipo_usuario',
                'managed': False,
            },
        ),
    ]
