# Generated by Django 2.0.6 on 2018-07-02 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ejemplo7', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cursos',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='departamento',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='rolusuariocurso',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='semestres',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tipousuario',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='usuarios',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='usuariotipousuario',
            options={'managed': True},
        ),
    ]
